<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('bookings', function (Blueprint $table) {
            $table->id();

            // Core relationships
            $table->foreignId('student_id')->constrained('users')->cascadeOnDelete();
            $table->foreignId('mentor_id')->constrained('mentors')->cascadeOnDelete();
            $table->foreignId('service_config_id')->constrained('services_config');
            $table->foreignId('mentor_availability_slot_id')->nullable()->constrained('mentor_availability_slots')->nullOnDelete();

            // Office Hours sessions get linked here; null for 1:1 / group bookings
            $table->foreignId('office_hour_session_id')->nullable()->constrained('office_hour_sessions')->nullOnDelete();

            // Session details
            $table->enum('session_type', ['1on1', '1on3', '1on5', 'office_hours'])->default('1on1');
            $table->unsignedTinyInteger('requested_group_size')->nullable();
            $table->timestamp('session_at');
            $table->string('session_timezone')->nullable(); // mentor/session timezone for UI rendering
            $table->integer('duration_minutes')->default(60);

            // Meeting link (generated by Zoom/Google Meet API on booking confirmation)
            $table->string('meeting_link')->nullable();
            $table->enum('meeting_type', ['zoom', 'google_meet'])->default('zoom');

            // Credits and price snapshot
            $table->integer('credits_charged')->default(1);
            $table->decimal('amount_charged', 8, 2)->default(0);
            $table->string('currency', 3)->default('USD');
            $table->json('pricing_snapshot')->nullable();

            // Status lifecycle
            // cancelled_pending_refund: cancelled but refund goes through support (as per template flow)
            $table->enum('status', [
                'pending',
                'confirmed',
                'completed',
                'cancelled',
                'cancelled_pending_refund',
                'no_show',
            ])->default('pending');
            $table->enum('approval_status', ['not_required', 'pending', 'approved', 'rejected'])->default('not_required');

            // Cancellation tracking
            $table->timestamp('cancelled_at')->nullable();
            $table->string('cancel_reason')->nullable();
            $table->foreignId('cancelled_by')->nullable()->constrained('users')->nullOnDelete();

            // Mandatory post-session feedback enforcement
            // Both flags must be true within 24hrs or platform restricts the user
            $table->timestamp('feedback_due_at')->nullable();
            $table->boolean('student_feedback_done')->default(false);
            $table->boolean('mentor_feedback_done')->default(false);

            // Group booking: one person pays for the full group
            $table->boolean('is_group_payer')->default(false);
            $table->foreignId('group_payer_id')->nullable()->constrained('users')->nullOnDelete();

            $table->timestamps();

            // Indexes for calendar, dashboard, and admin queries
            $table->index(['student_id', 'status', 'session_at']);
            $table->index(['mentor_id', 'status', 'session_at']);
            $table->index(['status', 'session_at']);
            $table->index(['approval_status', 'status']);
            $table->index('feedback_due_at');
            $table->index('session_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('bookings');
    }
};
